import{a as b,S as w,i}from"./assets/vendor-mdVVRe9K.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const L="46174966-07e02f6c406b1cfe44f6656da",T="https://pixabay.com/api/";async function p(o,t=1){try{const s=await b.get(`${T}`,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:12}});if(s.data.hits.length===0)throw new Error("No images found");return s.data}catch(s){throw console.error("Error fetching images:",s),s}}function y(o){const t=document.querySelector(".gallery"),s=o.map(({webformatURL:c,largeImageURL:e,tags:r,likes:n,views:g,comments:f,downloads:h})=>`
        <li class="gallery-item">
           <a href="${e}">
            <img src="${c}" alt="${r}" loading="lazy" class="preview-image"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${n}</p>
            <p><b>Views:</b> ${g}</p>
            <p><b>Comments:</b> ${f}</p>
            <p><b>Downloads:</b> ${h}</p>
          </div>
        </li>
      `).join("");t.innerHTML=s}const S=document.getElementById("search-form"),v=document.querySelector(".gallery"),l=document.getElementById("load-more"),a=document.querySelector(".loader");let m=1,u="";const d=new w(".gallery a");S.addEventListener("submit",async o=>{o.preventDefault(),u=o.currentTarget.elements.query.value.trim(),v.innerHTML="",m=1,l.style.display="none",a.style.display="block";try{await new Promise(s=>setTimeout(s,1e3));const t=await p(u,m);if(a.style.display="none",t.hits.length===0){i.error({message:"Sorry, no images found for your search query. Please try again!",position:"topRight",class:"custom-iziToast-error"});return}y(t.hits),d.refresh(),l.style.display="block"}catch(t){a.style.display="none",t.message==="No images found"?i.error({message:"Sorry, no images found for your search query. Please try again!",position:"topRight",class:"custom-iziToast-error"}):i.error({message:"Something went wrong, please try again later.",position:"topRight",class:"custom-iziToast-error"})}});l.addEventListener("click",async()=>{m+=1,a.style.display="block";try{await new Promise(t=>setTimeout(t,1e3));const o=await p(u,m);if(a.style.display="none",!o.hits||o.hits.length===0){i.info({message:"No more images available.",position:"topRight",class:"custom-iziToast-info"}),l.style.display="none";return}y(o.hits),d.refresh()}catch(o){a.style.display="none",o.message==="No images found"?(i.info({message:"No more images available.",position:"topRight",class:"custom-iziToast-info"}),l.style.display="none"):i.error({message:"Something went wrong, please try again later.",position:"topRight",class:"custom-iziToast-error"})}});
//# sourceMappingURL=index.js.map
